export const initialCategories = [
  {
    name: "料理",
    tasks: [
      { name: "家族のごはん", points: 100 },
      { name: "1人分皿洗い", points: 20 },
      { name: "炊飯", points: 20 },
      { name: "離乳食つくり1品", points: 100 },
      { name: "料理器具洗い", points: 20 },
      { name: "炊飯器セット洗い", points: 20 },
      { name: "ご飯冷凍", points: 20 },
      { name: "ナッツ瓶補充", points: 10 },
      { name: "デザート作り", points: 100 },
      { name: "お米米びつ入れ", points: 10 },
      { name: "お皿片付け", points: 20 },
      { name: "配膳", points: 20 },
      { name: "ディスポーザー処理", points: 10 },
      { name: "離乳食準備", points: 50 },
      { name: "離乳食をあげる", points: 50 },
    ],
  },
  {
    name: "洗濯",
    tasks: [
      { name: "洗濯洗い", points: 50 },
      { name: "洗濯干し", points: 50 },
      { name: "洗濯取り込み", points: 30 },
      { name: "特殊洗い", points: 300 },
      { name: "たたみ", points: 30 },
      { name: "ベビーベット洗い", points: 100 },
      { name: "布団干し", points: 500 },
    ],
  },
  {
    name: "掃除",
    tasks: [
      { name: "風呂掃除", points: 20 },
      { name: "ごみ捨て", points: 20 },
      { name: "トイレ便器掃除", points: 100 },
      { name: "トイレ床掃除", points: 50 },
      { name: "コロコロ", points: 10 },
      { name: "掃除機充電", points: 10 },
      { name: "部屋全体掃除", points: 100 },
      { name: "掃除機掃除", points: 50 },
      { name: "ディスポーザー洗", points: 300 },
    ],
  },
  {
    name: "その他家事",
    tasks: [
      { name: "加湿器水入れ", points: 10 },
      { name: "パキラ水やり", points: 10 },
      { name: "夜の戸締まり", points: 10 },
      { name: "ポスト確認", points: 10 },
      { name: "洗剤詰め替え", points: 10 },
    ],
  },
  {
    name: "子守",
    tasks: [
      { name: "授乳", points: 50 },
      { name: "オムツ変え", points: 20 },
      { name: "ウンチ変え", points: 50 },
      { name: "沐浴", points: 50 },
      { name: "ミルク", points: 50 },
      { name: "沐浴後ケア", points: 50 },
      { name: "お湯作り", points: 20 },
    ],
  },
];
